### ISSUE TITLE
Delete Cached File

### ISSUE THREAD

**Issue by erwinyusrizal** [mikeboers/Flask-Images#42]
Hi, Do you know how to delete the cached image from the cache folder? when the original file is deleted, I need to delete the cached image

Thanks

**Comment by iurisilvio** [comment]
I think the `Images.handle_request` abort if the file don't exist. https://github.com/mikeboers/Flask-Images/blob/master/flask_images/core.py#L324

**Comment by mikeboers** [comment]
@iurisilvio that's right.

I think @erwinyusrizal is going for automatically deleting the cached version when the original no longer exists. That code would slip neatly into where @iurisilvio just linked. It would only work for local images (as we will pull from remote services).

If you want to DIY, then I think the best thing would be to refactor so that you can compute the potential cache paths from a given source path and parameters, so that you can delete them all if you want to.

Perhaps a better forward thinking idea would be to drop metadata files beside all of the cache files indicating where they came from, so you can walk the cache folder to clean it up.

Personally, I've just deleted the whole cache folder on occasion and let it re-cache the images. I'm sure others may not be able to deal with that sort of overhead, so perhaps something like deleting cached files that were accessed more than a given threshold ago?
